<?php
session_start();
?>

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Experience</title>
    <link rel="stylesheet" href="css/reset.css">
    <link rel="stylesheet" href="css/stylesheet.css">
    <link href='https://fonts.googleapis.com/css?family=Pixelify Sans' rel='stylesheet'>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Inconsolata:wght@200..900&display=swap" rel="stylesheet">
  </head>
  <body class="blog_viewer_body">

  <div class="login_box">
    <?php if (isset($_SESSION['user_email'])): ?>
      <span>
        ✅ Welcome, <?= htmlspecialchars($_SESSION['user_email']) ?> |
        <a href="logout.php">Logout</a>
      </span>
    <?php else: ?>
      <span>
        ❌ You are not currently logged in |
        <a href="login.php">Login</a>
      </span>
    <?php endif; ?>
  </div>

  <div class="blog_post_head">
    <h1>Blog Posts</h1>
    <?php if (isset($_SESSION['user_email'])): ?>
        <a href="addEntry.php">-Make A New Post-</a><br><br>
    <?php else: ?>
        <p>You must be logged in to make a new post.</p><br>
    <?php endif; ?>
  </div>

<?php
$host = 'localhost';
$db = 'ecs417';
$user = 'root';
$pass = '';

try 
{
    $pdo = new PDO("mysql:host=$host;dbname=$db;charset=utf8mb4", $user, $pass);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

    // Fetch all posts unordered
    $stmt = $pdo->query("SELECT * FROM blog_posts");
    $posts = $stmt->fetchAll(PDO::FETCH_ASSOC);

    // Basic bubble sort algorithm generated by AI
  for ($i = 0; $i < count($posts) - 1; $i++) {
    for ($j = 0; $j < count($posts) - $i - 1; $j++) 
     {
            if (strtotime($posts[$j]['created_at']) < strtotime($posts[$j + 1]['created_at'])) 
        {
              $temp = $posts[$j];
              $posts[$j] = $posts[$j + 1];
              $posts[$j + 1] = $temp;
        }
     }
}

    if (count($posts) === 0) 
    {
        echo '<p>currently no active posts :(</p>';
    } 
    else 
    {
        foreach ($posts as $post) 
        {
            echo '<div class="blog_post_cont">';
            echo '<h2>' . htmlspecialchars($post['title']) . '</h2>';
            echo '<p>' . nl2br(htmlspecialchars($post['content'])) . '</p>';
            echo '<p class="created_at">Posted on: ' . htmlspecialchars($post['created_at']) . '</p>';
            echo '</div>';
        }
    }
} 
catch (PDOException $e) 
{
    echo "<p>Failed to load posts: " . $e->getMessage() . "</p>";
}
?>

    <div class="back_button">
        <a href="index.php">Back</a>
    </div>
    <div class="grid_item_5">
        <footer>© 2025 Lukas Rukevicius. All Rights Reserved</footer>
    </div>
  </body>
</html>